"""
Configuration for Pantip scraper.

This module contains all configuration variables used by the Pantip scraper,
including API endpoints, request parameters, and default values.
"""

from typing import Final

# Authorization token for Pantip API
# In production, this should be loaded from environment variables
AUTH_TOKEN: Final[str] = 'Basic dGVzdGVyOnRlc3Rlcg=='

# List of user agents to rotate for requests to avoid detection
USER_AGENTS: Final[list[str]] = [
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:77.0) Gecko/20100101 Firefox/77.0',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36',
]

# Request parameters
TOPICS_PER_PAGE: Final[int] = 10  # Number of topics per page in search results
TIMEOUT_SECONDS: Final[int] = 4  # Request timeout in seconds

# API Endpoints
SEARCH_API: Final[str] = "https://pantip.com/api/search-service/search/getresult"
TOPIC_BASE_URL: Final[str] = "https://pantip.com/topic/"
COMMENT_API: Final[str] = "https://pantip.com/forum/topic/render_comments"

ROOMS = [
    {
        "id": 100,
        "name": "รวมมิตร",
        "name_en": "all",
        "description": "รวมกระทู้จากทุกห้อง",
        "link_url": "https://pantip.com/forum",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-all.svg",
    },
    {
        "id": 31,
        "name": "บางขุนพรหม",
        "name_en": "tvshow",
        "description": "ละคร นักแสดง ซีรี่ส์ รายการโทรทัศน์ สถานีโทรทัศน์",
        "link_url": "https://pantip.com/forum/tvshow",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-tvshow.svg",
    },
    {
        "id": 9,
        "name": "ชายคา",
        "name_en": "home",
        "description": "บ้าน คอนโดมิเนียม ตกแต่งบ้าน เฟอร์นิเจอร์ เครื่องใช้ไฟฟ้า เครื่องครัว",
        "link_url": "https://pantip.com/forum/home",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-home.svg",
    },
    {
        "id": 10,
        "name": "ซิลิคอนวัลเลย์",
        "name_en": "siliconvalley",
        "description": "คอมมือใหม่ อินเทอร์เน็ต ซอฟต์แวร์ ฮาร์ดแวร์ เกม เขียนโปรแกรม Gadget",
        "link_url": "https://pantip.com/forum/siliconvalley",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-siliconvalley.svg",
    },
    {
        "id": 36,
        "name": "แก็ดเจ็ต",
        "name_en": "gadget",
        "description": "Gadget, Action Camera, Drone, Game Console, Smartwatch, Smartband",
        "link_url": "https://pantip.com/forum/gadget",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-gadget.svg",
    },
    {
        "id": 99,
        "name": "ไร้สังกัด",
        "name_en": "isolate",
        "description": "กระทู้อื่นๆ ที่ไม่สังกัดห้องไหนเลย",
        "link_url": "https://pantip.com/forum/isolate",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-isolate.svg",
    },
    {
        "id": 3,
        "name": "แกลเลอรี่",
        "name_en": "gallery",
        "description": "ภาพถ่ายบุคคล ภาพถ่ายทิวทัศน์ ภาพถ่ายมาโคร",
        "link_url": "https://pantip.com/forum/gallery",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-gallery.svg",
    },
    {
        "id": 28,
        "name": "กรีนโซน",
        "name_en": "greenzone",
        "description": "อนุรักษ์สิ่งแวดล้อม อนุรักษ์พลังงาน Green Living การออกแบบเพื่อสิ่งแวดล้อม ผลิตภัณฑ์รักษ์โลก เกษตรอินทรีย์",
        "link_url": "https://pantip.com/forum/greenzone",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-greenzone.svg",
    },
    {
        "id": 29,
        "name": "หอศิลป์",
        "name_en": "art",
        "description": "ศิลปะ ภาพวาด ประวัติศาสตร์ศิลป์ สื่อประสม Graphic Design",
        "link_url": "https://pantip.com/forum/art",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-art.svg",
    },
    {
        "id": 16,
        "name": "มาบุญครอง",
        "name_en": "mbk",
        "description": "โทรศัพท์มือถือ Smartphone Tablet iOS Android",
        "link_url": "https://pantip.com/forum/mbk",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-mbk.svg",
    },
    {
        "id": 11,
        "name": "โต๊ะเครื่องแป้ง",
        "name_en": "beauty",
        "description": "เครื่องสำอาง เสริมสวย แฟชั่น เครื่องประดับ ลดความอ้วน",
        "link_url": "https://pantip.com/forum/beauty",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-beauty.svg",
    },
    {
        "id": 8,
        "name": "ชานเรือน",
        "name_en": "family",
        "description": "ครอบครัว ตั้งครรภ์ ตั้งชื่อลูก การเลี้ยงลูก การสอนลูก",
        "link_url": "https://pantip.com/forum/family",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-family.svg",
    },
    {
        "id": 1,
        "name": "กล้อง",
        "name_en": "camera",
        "description": "กล้องถ่ายรูป กล้อง DSLR กล้องวิดีโอ เทคนิคการถ่ายรูป",
        "link_url": "https://pantip.com/forum/camera",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-camera.svg",
    },
    {
        "id": 2,
        "name": "ก้นครัว",
        "name_en": "food",
        "description": "ร้านอาหาร สูตรอาหาร อาหารคาว อาหารหวาน เบเกอรี่ ไอศกรีม",
        "link_url": "https://pantip.com/forum/food",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-food.svg",
    },
    {
        "id": 4,
        "name": "ไกลบ้าน",
        "name_en": "klaibann",
        "description": "เรียนต่อต่างประเทศ ทำงานต่างประเทศ วีซ่า",
        "link_url": "https://pantip.com/forum/klaibann",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-klaibann.svg",
    },
    {
        "id": 5,
        "name": "จตุจักร",
        "name_en": "jatujak",
        "description": "สัตว์เลี้ยง สุนัข แมว ต้นไม้ จัดสวน ของสะสม งานฝีมือ เกษตรกรรม",
        "link_url": "https://pantip.com/forum/jatujak",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-jatujak.svg",
    },
    {
        "id": 6,
        "name": "เฉลิมกรุง",
        "name_en": "chalermkrung",
        "description": "นักร้องนักดนตรี เพลง เครื่องดนตรี คอนเสิร์ต มิวสิควิดีโอ",
        "link_url": "https://pantip.com/forum/chalermkrung",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-chalermkrung.svg",
    },
    {
        "id": 7,
        "name": "เฉลิมไทย",
        "name_en": "chalermthai",
        "description": "ภาพยนตร์ ดาราภาพยนตร์ ค่ายหนัง เทศกาลหนัง หนังสั้น",
        "link_url": "https://pantip.com/forum/chalermthai",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-chalermthai.svg",
    },
    {
        "id": 12,
        "name": "ถนนนักเขียน",
        "name_en": "writer",
        "description": "แต่งนิยาย เรื่องสั้น กลอน นิทาน",
        "link_url": "https://pantip.com/forum/writer",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-writer.svg",
    },
    {
        "id": 13,
        "name": "บลูแพลนเน็ต",
        "name_en": "blueplanet",
        "description": "เที่ยวไทย เที่ยวต่างประเทศ ทะเล ภูเขา เกาะ น้ำตก ดำน้ำ สายการบิน",
        "link_url": "https://pantip.com/forum/blueplanet",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-blueplanet.svg",
    },
    {
        "id": 14,
        "name": "พันทิป",
        "name_en": "pantip",
        "description": "ข้อเสนอแนะถึงพันทิป วิธีการใช้งานพันทิป กิจกรรมพันทิป",
        "link_url": "https://pantip.com/forum/pantip",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-pantip.svg",
    },
    {
        "id": 15,
        "name": "ภูมิภาค",
        "name_en": "region",
        "description": "ภาคเหนือ ภาคอีสาน ภาคกลาง ภาคตะวันออก ภาคตะวันตก ภาคใต้",
        "link_url": "https://pantip.com/forum/region",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-region.svg",
    },
    {
        "id": 17,
        "name": "รัชดา",
        "name_en": "ratchada",
        "description": "รถยนต์ มอเตอร์ไซค์ เครื่องเสียงรถยนต์ แต่งรถ การจราจร",
        "link_url": "https://pantip.com/forum/ratchada",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-ratchada.svg",
    },
    {
        "id": 18,
        "name": "ราชดำเนิน",
        "name_en": "rajdumnern",
        "description": "การเมือง รัฐศาสตร์ กฎหมาย สภาผู้แทน รัฐบาล ฝ่ายค้าน พรรคการเมือง",
        "link_url": "https://pantip.com/forum/rajdumnern",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-rajdumnern.svg",
    },
    {
        "id": 19,
        "name": "ศาลาประชาคม",
        "name_en": "social",
        "description": "กฎหมาย ปัญหาสังคม ปัญหาชีวิต เศรษฐกิจ คุ้มครองผู้บริโภค",
        "link_url": "https://pantip.com/forum/social",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-social.svg",
    },
    {
        "id": 20,
        "name": "ศาสนา",
        "name_en": "religious",
        "description": "ศาสนาพุทธ ศาสนาคริสต์ ศาสนาอิสลาม เที่ยววัด ทำบุญ",
        "link_url": "https://pantip.com/forum/religious",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-religious.svg",
    },
    {
        "id": 21,
        "name": "ศุภชลาศัย",
        "name_en": "supachalasai",
        "description": "กีฬา ฟุตบอล บาสเกตบอล มวยสากล กอล์ฟ จักรยาน นักกีฬา",
        "link_url": "https://pantip.com/forum/supachalasai",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-supachalasai.svg",
    },
    {
        "id": 22,
        "name": "สยามสแควร์",
        "name_en": "siam",
        "description": "ชีวิตวัยรุ่น การเรียน โรงเรียน มหาวิทยาลัย ความรักวัยรุ่น เกม",
        "link_url": "https://pantip.com/forum/siam",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-siam.svg",
    },
    {
        "id": 23,
        "name": "สวนลุมพินี",
        "name_en": "lumpini",
        "description": "สุขภาพกาย สุขภาพจิต โรคมะเร็ง โรคไมเกรน โรคภูมิแพ้ ปวดประจำเดือน",
        "link_url": "https://pantip.com/forum/lumpini",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-lumpini.svg",
    },
    {
        "id": 24,
        "name": "สินธร",
        "name_en": "sinthorn",
        "description": "หุ้น เศรษฐกิจ การลงทุน LTF RMF ธนาคาร เงินตราต่างประเทศ",
        "link_url": "https://pantip.com/forum/sinthorn",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-sinthorn.svg",
    },
    {
        "id": 25,
        "name": "สีลม",
        "name_en": "silom",
        "description": "การบริหารจัดการ การตลาด ทรัพยากรบุคคล งานขาย SME ภาษีนิติบุคคล",
        "link_url": "https://pantip.com/forum/silom",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-silom.svg",
    },
    {
        "id": 26,
        "name": "หว้ากอ",
        "name_en": "wahkor",
        "description": "วิทยาศาสตร์ วิศวกรรม เทคโนโลยี ฟิสิกส์ ดาราศาสตร์ อวกาศ",
        "link_url": "https://pantip.com/forum/wahkor",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-wahkor.svg",
    },
    {
        "id": 27,
        "name": "ห้องสมุด",
        "name_en": "library",
        "description": "หนังสือ หนังสือนิยาย ภาษาไทย ภาษาจีน ภาษาอังกฤษ ปรัชญา ประวัติศาสตร์",
        "link_url": "https://pantip.com/forum/library",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-library.svg",
    },
    {
        "id": 30,
        "name": "การ์ตูน",
        "name_en": "cartoon",
        "description": "การ์ตูนญี่ปุ่น การ์ตูนไทย การ์ตูนฝรั่ง อนิเมะ วาดการ์ตูน ของสะสมจากการ์ตูน คอสเพลย์",
        "link_url": "https://pantip.com/forum/cartoon",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-cartoon.svg",
    },
    {
        "id": 32,
        "name": "บางรัก",
        "name_en": "bangrak",
        "description": "ความรัก แต่งงาน พรีเวดดิ้ง ปัญหาชีวิตคู่",
        "link_url": "https://pantip.com/forum/bangrak",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-bangrak.svg",
    },
    {
        "id": 33,
        "name": "พรหมชาติ",
        "name_en": "horoscope",
        "description": "ดูดวง ฮวงจุ้ย ไพ่ยิปซี ทำนายฝัน พระเครื่อง",
        "link_url": "https://pantip.com/forum/horoscope",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-horoscope.svg",
    },
    {
        "id": 34,
        "name": "ดิโอลด์สยาม",
        "name_en": "theoldsiam",
        "description": "ผู้สูงอายุ สุขภาพผู้สูงอายุ ชีวิตหลังเกษียณ สิทธิผู้สูงอายุ ท่องเที่ยวผู้สูงอายุ",
        "link_url": "https://pantip.com/forum/theoldsiam",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-theoldsiam.svg",
    },
    {
        "id": 35,
        "name": "กรุงโซล",
        "name_en": "korea",
        "description": "K-POP ซีรีส์เกาหลี นักแสดงเกาหลี อาหารเกาหลี เที่ยวเกาหลี แฟชั่นเกาหลี ภาษาเกาหลี",
        "link_url": "https://pantip.com/forum/korea",
        "room_icon_url": "https://ptcdn.info/mobile/icon_room/pt-forum-korea.svg",
    },
]
